name: loja_roupas
description: Demo/Beta - Loja Virtual de Roupas
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # Estado
  flutter_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  # Mídia
  image_picker: ^1.1.2
  http: ^1.2.2
  path: ^1.9.0
  
  # Firebase
  firebase_core: ^3.8.1
  cloud_firestore: ^5.5.1
  firebase_storage: ^12.3.7
  firebase_auth: ^5.3.4
  google_sign_in: ^6.2.2

  # Navegação
  go_router: ^14.6.2

  # UI / Utilitários
  cached_network_image: ^3.4.1
  flutter_svg: ^2.0.15
  intl: ^0.19.0
  uuid: ^4.5.1
  collection: ^1.18.0
  shared_preferences: ^2.5.3

  # Ícones
  cupertino_icons: ^1.0.8
  share_plus: ^13.3.0
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  riverpod_generator: ^2.6.2
  build_runner: ^2.4.13
  custom_lint: ^0.7.0
  riverpod_lint: ^2.6.2

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/